import { NextResponse } from "next/server";
import { supabaseAdmin } from "@/lib/supabase";
import { resend, getResendFromEmail, getResendToEmail } from "@/lib/resend";
import { AdminNotificationEmail } from "@/emails/AdminNotificationEmail";
import { ClientConfirmationEmail } from "@/emails/ClientConfirmationEmail";

/**
 * Helpers
 */
const getFormValue = (value: FormDataEntryValue | null) =>
  typeof value === "string" ? value.trim() : "";

const getOptionalFormValue = (value: FormDataEntryValue | null) =>
  typeof value === "string" ? value.trim() || null : null;

const createSafeFileName = (originalName: string) => {
  const ext = originalName.split(".").pop() || "bin";
  return `${Date.now()}-${Math.random().toString(36).slice(2)}.${ext}`;
};

async function uploadFileToSupabase(file: File) {
  const safeFileName = createSafeFileName(file.name);

  const arrayBuffer = await file.arrayBuffer();
  const fileBuffer = Buffer.from(arrayBuffer);

  const { error } = await supabaseAdmin.storage
    .from("commandes")
    .upload(safeFileName, fileBuffer, {
      contentType: file.type || "application/octet-stream",
      upsert: false,
    });

  if (error) {
    throw new Error(`Supabase upload failed: ${error.message}`);
  }

  const { data } = supabaseAdmin.storage
    .from("commandes")
    .getPublicUrl(safeFileName);

  return data.publicUrl;
}

/**
 * Route
 */
export async function POST(request: Request) {
  try {
    const formData = await request.formData();

    /**
     * Extract data
     */
    const name = getFormValue(formData.get("name"));
    const email = getFormValue(formData.get("email"));
    const projectType = getOptionalFormValue(formData.get("projectType"));
    const dimensions = getOptionalFormValue(formData.get("dimensions"));
    const budget = getOptionalFormValue(formData.get("budget"));
    const message = getFormValue(formData.get("message"));

    // Image generated by AI from the experience page
    const generatedImage = getOptionalFormValue(formData.get("generatedImage"));

    /**
     * Validation
     */
    if (!name || !email || !message) {
      return NextResponse.json(
        { error: "Les champs nom, email et message sont obligatoires." },
        { status: 400 },
      );
    }

    /**
     * File upload (optional)
     * Frontend sends the uploaded file with the field name "image"
     */
    let fileUrl: string | null = null;
    const file = formData.get("image");

    if (file instanceof File && file.size > 0) {
      try {
        fileUrl = await uploadFileToSupabase(file);
      } catch (uploadError) {
        console.error("Upload error:", uploadError);

        return NextResponse.json(
          {
            error: "Erreur lors de l’envoi du fichier.",
            details:
              uploadError instanceof Error
                ? uploadError.message
                : "Unknown upload error",
          },
          { status: 500 },
        );
      }
    }

    /**
     * Preview image for emails
     * Priority: uploaded file > generated image URL
     */
    const previewImage = fileUrl || generatedImage;

    /**
     * Insert into Supabase
     */
    const { data: insertedCommande, error: insertError } = await supabaseAdmin
      .from("commandes")
      .insert([
        {
          name,
          email,
          project_type: projectType,
          dimensions,
          budget,
          message,
          image_url: generatedImage,
          file_url: fileUrl,
          source: generatedImage ? "ai" : "manual",
          // status: "pending",
        },
      ])
      .select()
      .single();

    if (insertError) {
      console.error("Supabase insert error:", insertError);

      return NextResponse.json(
        {
          error: "Erreur lors de l’enregistrement de la demande.",
          details: insertError.message,
        },
        { status: 500 },
      );
    }

    /**
     * Send emails
     */
    const from = getResendFromEmail();
    const adminTo = getResendToEmail();

    let adminSent = false;
    let clientSent = false;

    try {
      const adminEmail = await resend.emails.send({
        from,
        to: adminTo,
        subject: `Nouvelle demande sur mesure | ${name}`,
        react: AdminNotificationEmail({
          name,
          email,
          message,
          projectType,
          dimensions,
          budget,
          imageUrl: previewImage,
          fileUrl,
        }),
      });

      adminSent = !adminEmail.error;

      if (adminEmail.error) {
        console.error("Admin email error:", adminEmail.error);
      }
    } catch (err) {
      console.error("Admin email exception:", err);
    }

    try {
      const clientEmail = await resend.emails.send({
        from,
        to: email,
        subject: "Nous avons bien reçu votre demande | Marcos Papermache",
        react: ClientConfirmationEmail({
          name,
          message,
          projectType,
          dimensions,
          budget,
          imageUrl: previewImage,
          fileUrl,
        }),
      });

      clientSent = !clientEmail.error;

      if (clientEmail.error) {
        console.error("Client email error:", clientEmail.error);
      }
    } catch (err) {
      console.error("Client email exception:", err);
    }

    /**
     * Success response
     */
    return NextResponse.json({
      success: true,
      message: "Demande envoyée avec succès.",
      commande: insertedCommande,
      emails: {
        adminSent,
        clientSent,
      },
    });
  } catch (error) {
    console.error("API route fatal error:", error);

    return NextResponse.json(
      {
        error: "Une erreur inattendue est survenue.",
        details: error instanceof Error ? error.message : "Unknown error",
      },
      { status: 500 },
    );
  }
}