import { NextResponse } from "next/server";
import { getAuthenticatedUser } from "@/lib/admin-auth";
import { prisma } from "@/lib/prisma";
import { supabaseAdmin } from "@/lib/supabase";
import { resend, getResendFromEmail, getResendToEmail } from "@/lib/resend";
import { AdminNotificationEmail } from "@/emails/AdminNotificationEmail";
import { ClientConfirmationEmail } from "@/emails/ClientConfirmationEmail";

/**
 * Helpers
 */
const getFormValue = (value: FormDataEntryValue | null) =>
  typeof value === "string" ? value.trim() : "";

const getOptionalFormValue = (value: FormDataEntryValue | null) =>
  typeof value === "string" ? value.trim() || null : null;

const createSafeFileName = (originalName: string) => {
  const ext = originalName.split(".").pop() || "bin";
  return `${Date.now()}-${Math.random().toString(36).slice(2)}.${ext}`;
};

async function uploadFileToSupabase(file: File) {
  const safeFileName = createSafeFileName(file.name);

  const arrayBuffer = await file.arrayBuffer();
  const fileBuffer = Buffer.from(arrayBuffer);

  const { error } = await supabaseAdmin.storage
    .from("commandes")
    .upload(safeFileName, fileBuffer, {
      contentType: file.type || "application/octet-stream",
      upsert: false,
    });

  if (error) {
    throw new Error(`Supabase upload failed: ${error.message}`);
  }

  const { data } = supabaseAdmin.storage
    .from("commandes")
    .getPublicUrl(safeFileName);

  return data.publicUrl;
}

async function uploadBase64ImageToSupabase(dataUrl: string): Promise<string> {
  const matches = dataUrl.match(/^data:([a-zA-Z0-9+/]+\/[a-zA-Z0-9+/]+);base64,(.+)$/);
  if (!matches) {
    throw new Error("Invalid data URL");
  }

  const mimeType = matches[1];
  const ext = mimeType.split("/")[1]?.replace("jpeg", "jpg") ?? "png";
  const fileName = `ai-${Date.now()}-${Math.random().toString(36).slice(2)}.${ext}`;
  const buffer = Buffer.from(matches[2], "base64");

  const { error } = await supabaseAdmin.storage
    .from("commandes")
    .upload(fileName, buffer, { contentType: mimeType, upsert: false });

  if (error) {
    throw new Error(`Supabase upload failed: ${error.message}`);
  }

  const { data } = supabaseAdmin.storage.from("commandes").getPublicUrl(fileName);
  return data.publicUrl;
}

/**
 * Route
 */
export async function POST(request: Request) {
  try {
    const formData = await request.formData();

    /**
     * Extract data
     */
    const name = getFormValue(formData.get("name"));
    const email = getFormValue(formData.get("email"));
    const projectType = getOptionalFormValue(formData.get("projectType"));
    const dimensions = getOptionalFormValue(formData.get("dimensions"));
    const budget = getOptionalFormValue(formData.get("budget"));
    const message = getFormValue(formData.get("message"));
    const referencePiece = getOptionalFormValue(formData.get("reference_piece"));

    // Image generated by AI from the experience page
    const generatedImage = getOptionalFormValue(formData.get("generatedImage"));
    const sourceAiImageId = getOptionalFormValue(formData.get("sourceAiImageId"));
    const prompt = getOptionalFormValue(formData.get("prompt"));

    // Attach the logged-in customer, if any, so it shows up in their dashboard
    const user = await getAuthenticatedUser();

    /**
     * Validation
     */
    if (!name || !email || !message) {
      return NextResponse.json(
        { error: "Les champs nom, email et message sont obligatoires." },
        { status: 400 },
      );
    }

    /**
     * File upload (optional)
     * Frontend sends the uploaded file with the field name "image"
     */
    let fileUrl: string | null = null;
    const file = formData.get("image");

    if (file instanceof File && file.size > 0) {
      try {
        fileUrl = await uploadFileToSupabase(file);
      } catch (uploadError) {
        console.error("Upload error:", uploadError);

        return NextResponse.json(
          {
            error: "Erreur lors de l’envoi du fichier.",
            details:
              uploadError instanceof Error
                ? uploadError.message
                : "Unknown upload error",
          },
          { status: 500 },
        );
      }
    }

    /**
     * Upload base64 AI image to Storage if needed
     */
    let imageUrl: string | null = null;
    if (generatedImage) {
      if (generatedImage.startsWith("data:")) {
        try {
          imageUrl = await uploadBase64ImageToSupabase(generatedImage);
        } catch (uploadErr) {
          console.error("AI image upload error:", uploadErr);
        }
      } else {
        imageUrl = generatedImage;
      }
    }

    /**
     * Preview image for emails
     * Priority: uploaded file > generated image URL
     */
    const previewImage = fileUrl || imageUrl;

    // Fold the reference piece into the stored message — the "commandes"
    // table has no dedicated column for it (schema is managed in Supabase,
    // not via Prisma migrations in this repo).
    const storedMessage = referencePiece
      ? `[Pièce de référence : ${referencePiece}]\n\n${message}`
      : message;

    /**
     * Insert into Supabase
     */
    const { data: insertedCommande, error: insertError } = await supabaseAdmin
      .from("commandes")
      .insert([
        {
          name,
          email,
          project_type: projectType,
          dimensions,
          budget,
          message: storedMessage,
          image_url: imageUrl,
          file_url: fileUrl,
          source: generatedImage ? "ai" : "manual",
          supabase_user_id: user?.id ?? null,
          source_ai_image_id: sourceAiImageId,
          prompt,
          // status: "pending",
        },
      ])
      .select()
      .single();

    // Claim the anonymous AI image, if any, now that we know who ordered it
    if (user && sourceAiImageId) {
      try {
        await prisma.generatedImage.updateMany({
          where: { id: sourceAiImageId, supabaseUserId: null },
          data: { supabaseUserId: user.id },
        });
      } catch (claimError) {
        console.error("Failed to claim AI image:", claimError);
      }
    }

    if (insertError) {
      console.error("Supabase insert error:", insertError);

      return NextResponse.json(
        {
          error: "Erreur lors de l’enregistrement de la demande.",
          details: insertError.message,
        },
        { status: 500 },
      );
    }

    /**
     * Send emails
     */
    const from = getResendFromEmail();
    const adminTo = getResendToEmail();

    let adminSent = false;
    let clientSent = false;
    let adminEmailError: string | null = null;
    let clientEmailError: string | null = null;

    try {
      const adminEmail = await resend.emails.send({
        from,
        to: adminTo,
        subject: `Nouvelle demande sur mesure | ${name}`,
        react: AdminNotificationEmail({
          name,
          email,
          message,
          projectType,
          dimensions,
          budget,
          imageUrl: previewImage,
          fileUrl,
          referencePiece,
        }),
      });

      adminSent = !adminEmail.error;

      if (adminEmail.error) {
        adminEmailError = `${adminEmail.error.name}: ${adminEmail.error.message}`;
        console.error("Admin email error:", JSON.stringify(adminEmail.error));
      }
    } catch (err) {
      adminEmailError = err instanceof Error ? err.message : "Unknown error";
      console.error("Admin email exception:", err);
    }

    try {
      const clientEmail = await resend.emails.send({
        from,
        to: email,
        subject: "Nous avons bien reçu votre demande | Marcos Papermache",
        react: ClientConfirmationEmail({
          name,
          message,
          projectType,
          dimensions,
          budget,
          imageUrl: previewImage,
          fileUrl,
          referencePiece,
        }),
      });

      clientSent = !clientEmail.error;

      if (clientEmail.error) {
        clientEmailError = `${clientEmail.error.name}: ${clientEmail.error.message}`;
        console.error("Client email error:", JSON.stringify(clientEmail.error));
      }
    } catch (err) {
      clientEmailError = err instanceof Error ? err.message : "Unknown error";
      console.error("Client email exception:", err);
    }

    /**
     * Success response
     */
    return NextResponse.json({
      success: true,
      message: "Demande envoyée avec succès.",
      commande: insertedCommande,
      emails: {
        adminSent,
        clientSent,
        ...(adminEmailError && { adminError: adminEmailError }),
        ...(clientEmailError && { clientError: clientEmailError }),
      },
    });
  } catch (error) {
    console.error("API route fatal error:", error);

    return NextResponse.json(
      {
        error: "Une erreur inattendue est survenue.",
        details: error instanceof Error ? error.message : "Unknown error",
      },
      { status: 500 },
    );
  }
}